name: barra2_ob53
experiment_uuid: 50268157-280e-4db6-8a66-01f2f548cfe8
description: Bureau of Meteorology Atmospheric Regional Reanalysis for Australia - Version 2 (BARRA2)
long_description: >-
  BARRA2 presents a moderate-resolution regional atmospheric reanalysis and a
  kilometre-scale downscaled reanalysis over Australia and surrounding regions,
  spanning from January 1979 to present day. It can be used for weather and
  climate research, case studies of past weather events, studying climate
  variability and developing climatology products, driving impact modelling
  (e.g., hydrological, coastal, and fire), evaluation and calibration of other
  modelling work (e.g., seasonal and climate projections).
model:
- UM
frequency:
- '1hr'
- '1day'
- '1mon'
- '3hr'
- 'subhr'
- 'fx'
variable:
- BWD01
- BWD01dir
- BWD03
- BWD03dir
- BWD06
- BWD06dir
- BWD09
- BWD09dir
- CAPE
- CAPEmax
- CIN
- CINmax
- clh
- clivi
- cll
- clm
- clt
- clwvi
- coltotdrym
- coltotwetm
- CRZdepth
- cw
- DCAPE
- DPL
- EBWD
- EBWDdir
- EFFCAPE
- EFFCIN
- EILbase
- EILdepth
- EMLbase
- EMLdepth
- EMLlapse
- ESRHl
- ESRHr
- evspsbl
- evspsblpot
- flashrate
- fogfraction
- FZL
- helicity
- helicitymax
- helicitymin
- hfls
- hfss
- HGZdepth
- hurs
- hus10
- hus100
- hus1000
- hus150
- hus20
- hus200
- hus250
- hus30
- hus300
- hus400
- hus50
- hus500
- hus600
- hus70
- hus700
- hus750
- hus800
- hus850
- hus900
- hus925
- hus950
- hus975
- huss
- LR01
- LR03
- LR24
- LR36
- LR75
- MAULbase
- MAULdepth
- MAULlapse
- maxcolrefl
- maxcolwa
- MLCAPbase
- MLCAPdepth
- MLCAPE
- MLCAPE03
- MLCAPEx
- MLCIN
- MLCIN1
- MLEL
- MLLCL
- MLLFC
- MLLMB
- MLLPLmixr
- MLLPLtemp
- MLSCLR
- MLSCRHmean
- MLVTEmax
- MLVTEmean
- mrfso
- mrfsol
- mrfsos
- mrro
- mrros
- mrso
- mrsol
- mrsos
- MUCAPE
- MUCAPE0m20
- MUCAPEm10m30
- MUCIN
- MUEL
- MUELtemp
- MULCL
- MULCLtemp
- MULFC
- MULMB
- MULPL
- MULPLmixr
- MULPLpres
- MULPLtemp
- MUVTEm10
- MUVTEm20
- MUVTEmax
- MUVTEmean
- omega500
- orog
- pr
- prc
- prga
- prhmax
- prmax
- prra
- prsn
- prsnmax
- prw
- ps
- psl
- PW
- qfluxu
- qfluxv
- radrefl1km
- RH01mean
- RH03mean
- RH24mean
- RH36mean
- rlds
- rldscs
- rlus
- rluscs
- rlut
- rlutcs
- rsds
- rsdscs
- rsdsdif
- rsdsdir
- rsdt
- rss
- rsus
- rsuscs
- rsut
- rsutcs
- SF
- sfcMoisflx
- sfcWind
- sfcWind10minmean
- sfcWindmax
- sftlf
- snd
- snm
- snw
- soildrainage
- SRH01l
- SRH01r
- SRH03l
- SRH03r
- SRH0500l
- SRH0500r
- sund
- ta10
- ta100
- ta1000
- ta100m
- ta150
- ta1500m
- ta150m
- ta20
- ta200
- ta200m
- ta250
- ta250m
- ta30
- ta300
- ta400
- ta50
- ta500
- ta50m
- ta600
- ta70
- ta700
- ta750
- ta800
- ta850
- ta900
- ta925
- ta950
- ta975
- tas
- tasmax
- tasmean
- tasmin
- tauu
- tauv
- throughfall
- ts
- tsl
- tsmean
- twiso
- twisomax
- twpse
- twpsemax
- U01mean
- U03mean
- U0500mean
- U06mean
- ua10
- ua100
- ua1000
- ua100m
- ua150
- ua1500m
- ua150m
- ua20
- ua200
- ua200m
- ua250
- ua250m
- ua30
- ua300
- ua400
- ua50
- ua500
- ua50m
- ua600
- ua70
- ua700
- ua750
- ua800
- ua850
- ua900
- ua925
- ua950
- ua975
- UANVmean
- uas
- uasmax
- uasmean
- UEILmean
- UESMadv
- USMadv
- USMdev
- V01mean
- V03mean
- V0500mean
- V06mean
- va10
- va100
- va1000
- va100m
- va150
- va1500m
- va150m
- va20
- va200
- va200m
- va250
- va250m
- va30
- va300
- va400
- va50
- va500
- va50m
- va600
- va70
- va700
- va750
- va800
- va850
- va900
- va925
- va950
- va975
- VANVmean
- vas
- vasmax
- vasmean
- VEILmean
- VESMadv
- visibility
- VSMadv
- VSMdev
- wa10
- wa100
- wa1000
- wa150
- wa20
- wa200
- wa250
- wa30
- wa300
- wa400
- wa50
- wa500
- wa600
- wa70
- wa700
- wa750
- wa800
- wa850
- wa900
- wa925
- wa950
- wa975
- wap10
- wap100
- wap1000
- wap150
- wap20
- wap200
- wap250
- wap30
- wap300
- wap400
- wap50
- wap500
- wap600
- wap70
- wap700
- wap750
- wap800
- wap850
- wap900
- wap925
- wap950
- wap975
- WBFZL
- wsgs
- wsgsmax
- z0
- zg10
- zg100
- zg1000
- zg150
- zg20
- zg200
- zg250
- zg30
- zg300
- zg400
- zg50
- zg500
- zg600
- zg70
- zg700
- zg750
- zg800
- zg850
- zg900
- zg925
- zg950
- zg975
- zmla
- ztp
nominal_resolution:
- 
version: 
contact: Bureau of Meteorology
email: data_governance_office@bom.gov.au
reference: >-
  Su, Chun-Hsu et. al. (2022) BARRA2: Development of the next-generation
  Australian regional atmospheric reanalysis (Bureau Research Report - 067),
  Bureau of Meteorology, Retrieved from
  http://www.bom.gov.au/research/publications/researchreports/BRR-067.pdf
license: CC-BY-4.0
url: https://dx.doi.org/10.25914/1x6g-2v48
parent_experiment:
related_experiments:
-
notes: 
keywords:
-
