name: access-nri-intake-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.13
  - access-py-telemetry
  - cftime
  - ecgtools>=2023.7.13
  - intake>=2.0.0
  - intake-dataframe-catalog>=0.3.1
  - intake-esm>=2025.2.3
  - jsonschema
  - pooch
  - pre-commit
  - pytest
  - xarray
  - pip
  - pip:
    - codecov
    - pytest-cov
    - yamanifest
