name: barpa_py18
experiment_uuid: 0cc28d8c-7ba5-11ef-a9ea-000007d3fe80
description: Bureau of Meteorology Atmospheric Regional Projections for Australia (BARPA)
long_description: >-
  BARPA Projections contains a moderate-resolution and a kilometre-scale regional climate projections over 
  Australia and surrounding regions. The current collections are developed based on CMIP6 global climate projections. 
  It consists of an ensemble of historical and future climate model fields. 
  It can be used for climate research, impact modelling, developing climatology products, and future likelihood products, 
  driving downstream impact modelling (e.g., hydrological, coastal, and fire), for case studies and stress testing 
  of environments, infrastructure and assets under different future scenarios.
model:
- CMIP6
frequency:
- '1hr'
- '1day'
- '1mon'
- '6hr'
- 'fx'
variable:
- evspsblpot
- vasmax
- zmla
- ta200m
- CAPE
- ta150m
- wsgsmax
- CIN
- va200m
- pr
- hfls
- rsut
- clwvi
- ta250m
- sfcWind
- cll
- clt
- ua300
- ta70
- ua1500m
- tsl
- va30
- ua400
- wa850
- mrros
- ua250
- hus10
- hus70
- rlut
- wa500
- va250m
- rlutcs
- wa700
- prw
- clivi
- ua50
- va100
- va700
- ua200m
- hus100
- rsdsdir
- vas
- snm
- hurs
- zg150
- psl
- va200
- wa600
- ps
- ua100
- va100m
- zg50
- rsdscs
- prc
- mrfso
- ua250m
- ua1000
- wa150
- ta400
- wa300
- wa50
- va500
- hus150
- va150
- sfcWindmax
- tasmin
- zg70
- wa250
- ta500
- mrsol
- wa70
- zg700
- ua925
- zg250
- ua10
- wa30
- zg400
- ua600
- va250
- ta950
- ua30
- va300
- wa400
- ua200
- ta150
- hus250
- ua70
- tauv
- zg30
- hfss
- vasmean
- rldscs
- ta50m
- mrfsos
- uas
- uasmean
- rsds
- clh
- tasmean
- mrsos
- rluscs
- uasmax
- ta1500m
- rsuscs
- ta20
- va50
- ua150m
- ta600
- prsn
- ta30
- zg300
- hus500
- mrfsol
- ta300
- zg200
- zg600
- hus1000
- ta10
- ta700
- ua500
- zg20
- rsutcs
- tauu
- ua100m
- va1500m
- rlds
- ta1000
- wa10
- hus400
- ta850
- ua700
- ta100
- zg925
- hus50
- rsdt
- zg100
- sic
- hus600
- hus700
- ta200
- ta50
- va10
- ts
- ta100m
- ua850
- hus20
- zg850
- hus850
- wa1000
- va1000
- snw
- rlus
- rsus
- va150m
- prhmax
- hus925
- tasmax
- va50m
- va925
- ua50m
- hus200
- ta925
- ua150
- snd
- ta250
- mrso
- hus30
- mrro
- wa20
- va70
- va400
- zg500
- z0
- omega500
- sund
- ua20
- va20
- clm
- va600
- wa925
- wa100
- zg10
- huss
- zg1000
- wa200
- va850
- tas
- hus300
- hus950
- sftlf
- evspsbl
- orog
nominal_resolution:
- 
version: 
contact: Bureau of Meteorology
email: data_governance_office@bom.gov.au
reference: >-
  Su, Chun-Hsu et. al. (2022). BARPA: New development of ACCESS-based regional
  climate modelling for Australian Climate Service. Bureau of Meteorology
  (Bureau Research Report - 069), Retrieved from
  http://www.bom.gov.au/research/publications/researchreports/BRR-069.pdf
license: CC-BY-4.0
url: https://dx.doi.org/10.25914/z1x6-dq28
parent_experiment:
related_experiments:
-
notes: 
keywords:
- cmip
