name: CD

on: [push, pull_request]

jobs:
  pypi:
    name: build and deploy to PyPI
    if: github.repository == 'ACCESS-NRI/access-nri-intake-catalog' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: python -m pip install build twine

      - name: Build distributions
        shell: bash -l {0}
        run: |
          git clean -xdf
          pyproject-build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  conda:
    name: build and deploy to conda
    needs: pypi
    if: always() && needs.pypi.result == 'success'
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: 3.11
          environment-file: .conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          
      - name: Enforce .tar.bz2 packages
        # Temporary work-arounds while the action uibcdf/action-build-and-upload-conda-packages gets updated:
        # We create a `~/.condarc` file with the correct options to enforce the use of `.tar.bz2` packages
        # and we set the channels to be used by conda build
        shell: bash
        run: |
            cat > ~/.condarc << EOF
            conda-build:
                pkg_format: .tar.bz2
            channels:
                - accessnri
                - conda-forge
                - nodefaults
            EOF

      - name: Build and upload the conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: .conda
          python-version: 3.11
          user: accessnri
          label: main
          token: ${{ secrets.anaconda_token }}

